# name: Python

# on:
#   workflow_dispatch:
#   schedule:
#     - cron: "5 */3 * * *"
#   push:
#     branches: ["main"]

# jobs:
#   run:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read

#     steps:
#       - name: Checkout do código
#         uses: actions/checkout@v4

#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.12"

#       - name: Instalar dependências
#         run: |
#           python -m pip install --upgrade pip --quiet
#           if [ -f requirements.txt ]; then pip install -r requirements.txt --quiet; fi

#       - name: Executar script Python
#         env:
#           URL: ${{ secrets.URL }}
#           TOKENS: ${{ secrets.TOKENS }}
#           USER_AGENT: ${{ secrets.USER_AGENT }}
#         timeout-minutes: 10
#         run: python app.py
